apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: devfile-sample
  labels: 
    component: devfile-sample
  annotations:
    github.com/project-slug: rohitkrai03/devfile-sample
    backstage.io/kubernetes-id: devfile-sample
    quay.io/repository-slug: quayadmin/my-quarkus-app,
    janus-idp.io/tekton : devfile-sample
spec:
  type: service
  lifecycle: unknown
  owner: temp-team-a
