apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: devfile-sample
  labels: 
    component: devfile-sample
  annotations:
    github.com/project-slug: rohitkrai03/devfile-sample
    backstage.io/kubernetes-id: devfile-sample
    quay.io/repository-slug: quayadmin/my-quarkus-app
    janus-idp.io/tekton : devfile-sample
spec:
  type: service
  lifecycle: unknown
  owner: rohitkrai03
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-rhdh-ai
  description: Team RHDH Plugins and AI
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: rohitkrai03@gmail.com
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: rohitkrai03
spec:
  profile:
    # Intentional no displayName for testing
    email: rohitkrai03@gmail.com
  memberOf: [team-rhdh-ai]
